### ISSUE TITLE
Fix `octikit.authenticate() is deprecated` warning

### ISSUE THREAD

**Issue by mrcasals** [waffleio/gh-actions#18]
I'm using your `action-prmonorepolabel` action and it works as expected, but I get some warnings when running it:

```
action "LabelRepos" {
  uses = "waffleio/gh-actions/action-prmonorepolabel@master"
  secrets = ["GITHUB_TOKEN"]
}
```

```
Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/action/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:4:26)
    at Object.<anonymous> (/action/app.js:11:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Can you check them?

Thanks! 😄

**Comment by adamzolyak** [comment]
resolved by adamzolyak/monorepo-pr-labeler-action#3

**Comment by adamzolyak** [comment]
Closing as a duplicate.  It will be resolved in adamzolyak/monorepo-pr-labeler-action#2.  Thanks again for opening an issue!

**Comment by adamzolyak** [comment]
@mrcasals updated GH Action w/ this update released https://github.com/marketplace/actions/monorepo-pr-repo-labeler?version=1.1.1
